const IngredientsData = [
	{
		id: 0,
		name: "Beetle Scuttle",
		effects: ["Breach", "Increase Armor", "Protection", "Vitality"],
		effect1: "Breach",
		effect2: "Increase Armor",
		effect3: "Protection",
		effect4: "Vitality",
		src: "/images/ingredients/Beetle_Scuttle.png",
	},
	{
		id: 1,
		name: "Blessed Thistle",
		effects: ["Restore Stamina", "Increase Weapon Power", "Ravage Health", "Speed"],
		effect1: "Restore Stamina",
		effect2: "Increase Weapon Power",
		effect3: "Ravage Health",
		effect4: "Speed",
		src: "/images/ingredients/Blessed_Thistle.png",
	},
	{
		id: 2,
		name: "Blue Entoloma",
		effects: ["Ravage Magicka", "Cowardice", "Restore Health", "Invisible"],
		effect1: "Ravage Magicka",
		effect2: "Cowardice",
		effect3: "Restore Health",
		effect4: "Invisible",
		src: "/images/ingredients/Blue_Entoloma.png",
	},
	{
		id: 3,
		name: "Bugloss",
		effects: ["Increase Spell Resist", "Restore Health", "Cowardice", "Restore Magicka"],
		effect1: "Increase Spell Resist",
		effect2: "Restore Health",
		effect3: "Cowardice",
		effect4: "Restore Magicka",
		src: "/images/ingredients/Bugloss.png",
	},
	{
		id: 4,
		name: "Butterfly Wing",
		effects: ["Restore Health", "Lingering Health", "Uncertainty", "Vitality"],
		effect1: "Restore Health",
		effect2: "Lingering Health",
		effect3: "Uncertainty",
		effect4: "Vitality",
		src: "/images/ingredients/Butterfly_Wing.png",
	},
	{
		id: 5,
		name: "Chaurus Egg",
		effects: ["Timidity", "Ravage Magicka", "Restore Stamina", "Detection"],
		effect1: "Timidity",
		effect2: "Ravage Magicka",
		effect3: "Restore Stamina",
		effect4: "Detection",
		src: "/images/ingredients/Chaurus_Egg.png",
	},
	{
		id: 6,
		name: "Clam Gall",
		effects: ["Increase Spell Resist", "Hindrance", "Vulnerability", "Defile"],
		effect1: "Increase Spell Resist",
		effect2: "Hindrance",
		effect3: "Vulnerability",
		effect4: "Defile",
		src: "/images/ingredients/Clam_Gall.png",
	},
	{
		id: 7,
		name: "Columbine",
		effects: ["Restore Health", "Restore Magicka", "Restore Stamina", "Unstoppable"],
		effect1: "Restore Health",
		effect2: "Restore Magicka",
		effect3: "Restore Stamina",
		effect4: "Unstoppable",
		src: "/images/ingredients/Columbine.png",
	},
	{
		id: 8,
		name: "Corn Flower",
		effects: ["Restore Magicka", "Increase Spell Power", "Ravage Health", "Detection"],
		effect1: "Restore Magicka",
		effect2: "Increase Spell Power",
		effect3: "Ravage Health",
		effect4: "Detection",
		src: "/images/ingredients/Corn_Flower.png",
	},
	{
		id: 9,
		name: "Crimson Nirnroot",
		effects: ["Timidity", "Spell Critical", "Gradual Ravage Health", "Restore Health"],
		effect1: "Timidity",
		effect2: "Spell Critical",
		effect3: "Gradual Ravage Health",
		effect4: "Restore Health",
		src: "/images/ingredients/Crimson_Nirnroot.png",
	},
	{
		id: 10,
		name: "Dragon's Bile",
		effects: ["Heroism", "Vulnerability", "Invisible", "Vitality"],
		effect1: "Heroism",
		effect2: "Vulnerability",
		effect3: "Invisible",
		effect4: "Vitality",
		src: "/images/ingredients/Dragons_Bile.png",
	},
	{
		id: 11,
		name: "Dragon's Blood",
		effects: ["Lingering Health", "Restore Health", "Heroism", "Defile"],
		effect1: "Lingering Health",
		effect2: "Restore Stamina",
		effect3: "Heroism",
		effect4: "Defile",
		src: "/images/ingredients/Dragons_Blood.png",
	},
	{
		id: 12,
		name: "Dragon Rheum",
		effects: ["Restore Magicka", "Enervation", "Heroism", "Speed"],
		effect1: "Restore Magicka",
		effect2: "Enervation",
		effect3: "Heroism",
		effect4: "Speed",
		src: "/images/ingredients/Dragon_Rheum.png",
	},
	{
		id: 13,
		name: "Dragonthorn",
		effects: ["Increase Weapon Power", "Restore Stamina", "Fracture", "Weapon Critical"],
		effect1: "Increase Weapon Power",
		effect2: "Restore Stamina",
		effect3: "Fracture",
		effect4: "Weapon Critical",
		src: "/images/ingredients/Dragonthorn.png",
	},
	{
		id: 14,
		name: "Emetic Russula",
		effects: ["Ravage Health", "Ravage Magicka", "Ravage Stamina", "Entrapment"],
		effect1: "Ravage Health",
		effect2: "Ravage Magicka",
		effect3: "Ravage Stamina",
		effect4: "Entrapment",
		src: "/images/ingredients/Emetic_Russula.png",
	},
	{
		id: 15,
		name: "Fleshfly Larva",
		effects: ["Ravage Stamina", "Vulnerability", "Gradual Ravage Health", "Vitality"],
		effect1: "Ravage Stamina",
		effect2: "Vulnerability",
		effect3: "Gradual Ravage Health",
		effect4: "Vitality",
		src: "/images/ingredients/Fleshfly_Larva.png",
	},
	{
		id: 16,
		name: "Imp Stool",
		effects: ["Maim", "Ravage Stamina", "Increase Armor", "Enervation"],
		effect1: "Maim",
		effect2: "Ravage Stamina",
		effect3: "Increase Armor",
		effect4: "Enervation",
		src: "/images/ingredients/Imp_Stool.png",
	},
	{
		id: 17,
		name: "Lady's Smock",
		effects: ["Increase Spell Power", "Restore Magicka", "Breach", "Spell Critical"],
		effect1: "Increase Spell Power",
		effect2: "Restore Magicka",
		effect3: "Breach",
		effect4: "Spell Critical",
		src: "/images/ingredients/Ladys_Smock.png",
	},
	{
		id: 18,
		name: "Luminous Russula",
		effects: ["Ravage Stamina", "Maim", "Restore Health", "Hindrance"],
		effect1: "Ravage Stamina",
		effect2: "Maim",
		effect3: "Restore Health",
		effect4: "Hindrance",
		src: "/images/ingredients/Luminous_Russula.png",
	},
	{
		id: 19,
		name: "Mountain Flower",
		effects: ["Increase Armor", "Restore Health", "Maim", "Restore Stamina"],
		effect1: "Increase Armor",
		effect2: "Restore Health",
		effect3: "Maim",
		effect4: "Restore Stamina",
		src: "/images/ingredients/Mountain_Flower.png",
	},
	{
		id: 20,
		name: "Mudcrab Chitin",
		effects: ["Increase Spell Resist", "Increase Armor", "Protection", "Defile"],
		effect1: "Increase Spell Resist",
		effect2: "Increase Armor",
		effect3: "Protection",
		effect4: "Defile",
		src: "/images/ingredients/Mudcrab_Chitin.png",
	},
	{
		id: 21,
		name: "Namira's Rot",
		effects: ["Spell Critical", "Speed", "Invisible", "Unstoppable"],
		effect1: "Spell Critical",
		effect2: "Speed",
		effect3: "Invisible",
		effect4: "Unstoppable",
		src: "/images/ingredients/Namiras_Rot.png",
	},
	{
		id: 22,
		name: "Nightshade",
		effects: ["Ravage Health", "Protection", "Gradual Ravage Health", "Defile"],
		effect1: "Ravage Health",
		effect2: "Protection",
		effect3: "Gradual Ravage Health",
		effect4: "Defile",
		src: "/images/ingredients/Nightshade.png",
	},
	{
		id: 23,
		name: "Nirnroot",
		effects: ["Ravage Health", "Uncertainty", "Enervation", "Invisible"],
		effect1: "Ravage Health",
		effect2: "Uncertainty",
		effect3: "Enervation",
		effect4: "Invisible",
		src: "/images/ingredients/Nirnroot.png",
	},
	{
		id: 24,
		name: "Powdered Mother of Pearl",
		effects: ["Lingering Health", "Speed", "Vitality", "Protection"],
		effect1: "Lingering Health",
		effect2: "Speed",
		effect3: "Vitality",
		effect4: "Protection",
		src: "/images/ingredients/Powdered_Mother_of_Pearl.png",
	},
	{
		id: 25,
		name: "Scrib Jelly",
		effects: ["Ravage Magicka", "Speed", "Vulnerability", "Lingering Health"],
		effect1: "Ravage Magicka",
		effect2: "Speed",
		effect3: "Vulnerability",
		effect4: "Lingering Health",
		src: "/images/ingredients/Scrib_Jelly.png",
	},
	{
		id: 26,
		name: "Spider Egg",
		effects: ["Hindrance", "Invisible", "Lingering Health", "Defile"],
		effect1: "Hindrance",
		effect2: "Invisible",
		effect3: "Lingering Health",
		effect4: "Defile",
		src: "/images/ingredients/Spider_Egg.png",
	},
	{
		id: 27,
		name: "Stinkhorn",
		effects: ["Fracture", "Ravage Health", "Increase Weapon Power", "Ravage Stamina"],
		effect1: "Fracture",
		effect2: "Ravage Health",
		effect3: "Increase Weapon Power",
		effect4: "Ravage Stamina",
		src: "/images/ingredients/Stinkhorn.png",
	},
	{
		id: 28,
		name: "Torchbug Thorax",
		effects: ["Fracture", "Enervation", "Detection", "Vitality"],
		effect1: "Fracture",
		effect2: "Enervation",
		effect3: "Detection",
		effect4: "Vitality",
		src: "/images/ingredients/Torchbug_Thorax.png",
	},
	{
		id: 29,
		name: "Vile Coagulant",
		effects: ["Timidity", "Ravage Health", "Restore Magicka", "Protection"],
		effect1: "Timidity",
		effect2: "Ravage Health",
		effect3: "Restore Magicka",
		effect4: "Protection",
		src: "/images/ingredients/Vile_Coagulant.png",
	},
	{
		id: 30,
		name: "Violet Coprinus",
		effects: ["Breach", "Ravage Health", "Increase Spell Power", "Ravage Magicka"],
		effect1: "Breach",
		effect2: "Ravage Health",
		effect3: "Increase Spell Power",
		effect4: "Ravage Magicka",
		src: "/images/ingredients/Violet_Coprinus.png",
	},
	{
		id: 31,
		name: "Water Hyacinth",
		effects: ["Restore Health", "Spell Critical", "Weapon Critical", "Entrapment"],
		effect1: "Restore Health",
		effect2: "Spell Critical",
		effect3: "Weapon Critical",
		effect4: "Entrapment",
		src: "/images/ingredients/Water_Hyacinth.png",
	},
	{
		id: 32,
		name: "White Cap",
		effects: ["Cowardice", "Ravage Magicka", "Increase Spell Resist", "Detection"],
		effect1: "Cowardice",
		effect2: "Ravage Magicka",
		effect3: "Increase Spell Resist",
		effect4: "Detection",
		src: "/images/ingredients/White_Cap.png",
	},
	{
		id: 33,
		name: "Wormwood",
		effects: ["Weapon Critical", "Hindrance", "Detection", "Unstoppable"],
		effect1: "Weapon Critical",
		effect2: "Hindrance",
		effect3: "Detection",
		effect4: "Unstoppable",
		src: "/images/ingredients/Wormwood.png",
	}
];

export default IngredientsData;